### ISSUE TITLE
如果能设定运行时间范围就好了

### ISSUE THREAD

**Issue by RipperPix00** [hyydsz/NoSleepHD#1]
比如我白天使用电脑，晚上挂机，其实挂机就没必要一直让硬盘运转了，作者可否增加一个设定时间范围的功能

**Comment by hyydsz** [comment]
要过几天再更新了

**Comment by RipperPix00** [comment]
那实在是太棒了！

**Comment by hyydsz** [comment]
更新完了 去测测有没有bug吧

**Comment by RipperPix00** [comment]
感谢作者更新，我下载了新版本，不过我现在只要打开软件，软件就会立马卡死😥

**Comment by hyydsz** [comment]
试试清除注册表
在cmd输入reg delete HKEY_CURRENT_USER\Software\NoSleepHD /f

**Comment by RipperPix00** [comment]
> 试试清除注册表 在cmd输入reg delete HKEY_CURRENT_USER\Software\NoSleepHD /f

我删除了你说的注册表，没有解决程序无响应的问题。无响应的问题发生在点开“定时”按钮的那一刻，然后只能强行关闭，再次打开就会直接无响应，只能删除注册表才能再次正常打开软件。

**Comment by hyydsz** [comment]
[https://github.com/hyydsz/NoSleepHD/releases/latest](最新版) 我发现了bug 定时的代码中有一处陷入了死循环
