### ISSUE TITLE
硬盘数量超过四个后显示不全

### ISSUE THREAD

**Issue by infrost** [hyydsz/NoSleepHD#2]
如题，见下图：无法选择到`L`盘，且无滚动条，改变窗口大小后`L`盘选项仍不可见

![image](https://github.com/user-attachments/assets/71bfb4cf-6b64-4e3f-a453-5a98e813be13)

**Comment by hyydsz** [comment]
[https://github.com/hyydsz/NoSleepHD/releases/tag/2.2.2](最新版) 把屎山代码重写了一遍
